 

ALTER TABLE @OWNER_SCHEMA.actor ADD CONSTRAINT PK_Actor PRIMARY KEY (actor_id);

ALTER TABLE @OWNER_SCHEMA.address ADD CONSTRAINT PK_Address PRIMARY KEY (address_id);

ALTER TABLE @OWNER_SCHEMA.category ADD CONSTRAINT PK_Category PRIMARY KEY (category_id);

ALTER TABLE @OWNER_SCHEMA.city ADD CONSTRAINT PK_City PRIMARY KEY (city_id);

ALTER TABLE @OWNER_SCHEMA.country ADD CONSTRAINT PK_Country PRIMARY KEY (country_id);

ALTER TABLE @OWNER_SCHEMA.customer ADD CONSTRAINT PK_Customer PRIMARY KEY (customer_id);

ALTER TABLE @OWNER_SCHEMA.film_actor ADD CONSTRAINT PK_FilmActor PRIMARY KEY (actor_id, film_id);

ALTER TABLE @OWNER_SCHEMA.film_category ADD CONSTRAINT PK_FilmCategory PRIMARY KEY (film_id, category_id);

ALTER TABLE @OWNER_SCHEMA.film ADD CONSTRAINT PK_Film PRIMARY KEY (film_id);

ALTER TABLE @OWNER_SCHEMA.inventory ADD CONSTRAINT PK_Inventory PRIMARY KEY (inventory_id);

ALTER TABLE @OWNER_SCHEMA.language ADD CONSTRAINT PK_Language PRIMARY KEY (language_id);

ALTER TABLE @OWNER_SCHEMA.payment ADD CONSTRAINT PK_Payment PRIMARY KEY (payment_id);

ALTER TABLE @OWNER_SCHEMA.rental ADD CONSTRAINT PK_Rental PRIMARY KEY (rental_id);

ALTER TABLE @OWNER_SCHEMA.staff ADD CONSTRAINT PK_Staff PRIMARY KEY (staff_id);

ALTER TABLE @OWNER_SCHEMA.store ADD CONSTRAINT PK_Store PRIMARY KEY (store_id);