
ALTER TABLE @OWNER_SCHEMA.city ADD CONSTRAINT FK_City_0 FOREIGN KEY (country_id) REFERENCES @OWNER_SCHEMA.country(country_id);


ALTER TABLE @OWNER_SCHEMA.customer ADD CONSTRAINT FK_Customer_0 FOREIGN KEY (store_id) REFERENCES @OWNER_SCHEMA.store(store_id);
ALTER TABLE @OWNER_SCHEMA.customer ADD CONSTRAINT FK_Customer_1 FOREIGN KEY (address_id) REFERENCES @OWNER_SCHEMA.address(address_id);

 
ALTER TABLE @OWNER_SCHEMA.film_actor ADD CONSTRAINT FK_FilmActor_0 FOREIGN KEY (film_id) REFERENCES @OWNER_SCHEMA.film(film_id);


ALTER TABLE @OWNER_SCHEMA.film_category ADD CONSTRAINT FK_FilmCategory_0 FOREIGN KEY (film_id) REFERENCES @OWNER_SCHEMA.film(film_id);
ALTER TABLE @OWNER_SCHEMA.film_category ADD CONSTRAINT FK_FilmCategory_1 FOREIGN KEY (category_id) REFERENCES @OWNER_SCHEMA.category(category_id);


ALTER TABLE @OWNER_SCHEMA.film ADD CONSTRAINT FK_Film_0 FOREIGN KEY (language_id) REFERENCES @OWNER_SCHEMA.language(language_id);
ALTER TABLE @OWNER_SCHEMA.film ADD CONSTRAINT FK_Film_1 FOREIGN KEY (original_language_id) REFERENCES @OWNER_SCHEMA.language(language_id);


ALTER TABLE @OWNER_SCHEMA.inventory ADD CONSTRAINT FK_Inventory_0 FOREIGN KEY (film_id) REFERENCES @OWNER_SCHEMA.film(film_id);
ALTER TABLE @OWNER_SCHEMA.inventory ADD CONSTRAINT FK_Inventory_1 FOREIGN KEY (store_id) REFERENCES @OWNER_SCHEMA.store(store_id);


ALTER TABLE @OWNER_SCHEMA.payment ADD CONSTRAINT FK_Payment_0 FOREIGN KEY (customer_id) REFERENCES @OWNER_SCHEMA.customer(customer_id);
ALTER TABLE @OWNER_SCHEMA.payment ADD CONSTRAINT FK_Payment_1 FOREIGN KEY (staff_id) REFERENCES @OWNER_SCHEMA.staff(staff_id);
ALTER TABLE @OWNER_SCHEMA.payment ADD CONSTRAINT FK_Payment_2 FOREIGN KEY (rental_id) REFERENCES @OWNER_SCHEMA.rental(rental_id);


ALTER TABLE @OWNER_SCHEMA.rental ADD CONSTRAINT FK_Rental_0 FOREIGN KEY (inventory_id) REFERENCES @OWNER_SCHEMA.inventory(inventory_id);
ALTER TABLE @OWNER_SCHEMA.rental ADD CONSTRAINT FK_Rental_1 FOREIGN KEY (customer_id) REFERENCES @OWNER_SCHEMA.customer(customer_id);
ALTER TABLE @OWNER_SCHEMA.rental ADD CONSTRAINT FK_Rental_2 FOREIGN KEY (staff_id) REFERENCES @OWNER_SCHEMA.staff(staff_id);

ALTER TABLE @OWNER_SCHEMA.staff ADD CONSTRAINT FK_Staff_0 FOREIGN KEY (store_id) REFERENCES @OWNER_SCHEMA.store(store_id);
ALTER TABLE @OWNER_SCHEMA.staff ADD CONSTRAINT FK_Staff_1 FOREIGN KEY (address_id) REFERENCES @OWNER_SCHEMA.address(address_id);


ALTER TABLE @OWNER_SCHEMA.store ADD CONSTRAINT FK_Store_1 FOREIGN KEY (manager_staff_id) REFERENCES @OWNER_SCHEMA.staff(staff_id);
ALTER TABLE @OWNER_SCHEMA.store ADD CONSTRAINT FK_Store_0 FOREIGN KEY (address_id) REFERENCES @OWNER_SCHEMA.address(address_id);